final Map<String, String> turkish_labels = {
  'person': 'insan',
  'bicycle': 'bisiklet',
  'car': 'araba',
  'motorcycle': 'motosiklet',
  'airplane': 'uçak',
  'bus': 'otobüs',
  'train': 'tren',
  'truck': 'kamyon',
  'boat': 'tekne',
  'traffic light': 'trafik ışığı',
  'fire hydrant': 'yangın musluğu',
  'stop sign': 'dur tabelası',
  'parking meter': 'parkmetre',
  'bench': 'bank',
  'bird': 'kuş',
  'cat': 'kedi',
  'dog': 'köpek',
  'horse': 'at',
  'sheep': 'koyun',
  'cow': 'inek',
  'elephant': 'fil',
  'bear': 'ayı',
  'zebra': 'zebra',
  'giraffe': 'zürafa',
  'backpack': 'sırt çantası',
  'umbrella': 'şemsiye',
  'handbag': 'el çantası',
  'tie': 'kravat',
  'suitcase': 'bavul',
  'frisbee': 'frizbi',
  'skis': 'kayak',
  'snowboard': 'kar kayağı',
  'sports ball': 'top',
  'kite': 'uçurtma',
  'baseball bat': 'beyzbol sopası',
  'baseball glove': 'beyzbol eldiveni',
  'skateboard': 'kaykay',
  'surfboard': 'sörf tahtası',
  'tennis racket': 'tenis raketi',
  'bottle': 'şişe',
  'wine glass': 'şarap kadehi',
  'cup': 'fincan',
  'fork': 'çatal',
  'knife': 'bıçak',
  'spoon': 'kaşık',
  'bowl': 'kase',
  'banana': 'muz',
  'apple': 'elma',
  'sandwich': 'sandviç',
  'orange': 'portakal',
  'broccoli': 'brokoli',
  'carrot': 'havuç',
  'hot dog': 'sosisli sandviç',
  'pizza': 'pizza',
  'donut': 'çörek',
  'cake': 'kek',
  'chair': 'sandalye',
  'couch': 'kanepe',
  'potted plant': 'saksı bitkisi',
  'bed': 'yatak',
  'dining table': 'yemek masası',
  'toilet': 'tuvalet',
  'tv': 'televizyon',
  'laptop': 'dizüstü bilgisayar',
  'mouse': 'fare',
  'remote': 'uzaktan kumanda',
  'keyboard': 'klavye',
  'cell phone': 'cep telefonu',
  'microwave': 'mikrodalga fırın',
  'oven': 'fırın',
  'toaster': 'tost makinesi',
  'sink': 'lavabo',
  'refrigerator': 'buzdolabı',
  'book': 'kitap',
  'clock': 'saat',
  'vase': 'vazo',
  'scissors': 'makas',
  'teddy bear': 'oyuncak ayı',
  'hair drier': 'saç kurutma makinesi',
  'toothbrush': 'diş fırçası',
  'tree': 'ağaç',
  'building': 'bina',
  'wall': 'duvar',
  'door': 'kapı',
  'window': 'pencere',
  'table': 'masa',
  'flower': 'çiçek',
  'plant': 'bitki',
};
